# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tset.proto\x12\x0bndb.request\x1a\x1cgoogle/protobuf/struct.proto\"*\n\x03Set\x12#\n\x02kv\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x13\n\x03Get\x12\x0c\n\x04keys\x18\x02 \x03(\t\"Q\n\x07Request\x12\x1f\n\x03get\x18\x01 \x01(\x0b\x32\x10.ndb.request.GetH\x00\x12\x1f\n\x03set\x18\x02 \x01(\x0b\x32\x10.ndb.request.SetH\x00\x42\x04\n\x02kvB\x02H\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'set_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _SET._serialized_start=56
  _SET._serialized_end=98
  _GET._serialized_start=100
  _GET._serialized_end=119
  _REQUEST._serialized_start=121
  _REQUEST._serialized_end=202
# @@protoc_insertion_point(module_scope)
