# automatically generated by the FlatBuffers compiler, do not modify

# namespace: response

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class KVRmv(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KVRmv()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKVRmv(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KVRmv
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def KVRmvStart(builder):
    builder.StartObject(0)

def Start(builder):
    KVRmvStart(builder)

def KVRmvEnd(builder):
    return builder.EndObject()

def End(builder):
    return KVRmvEnd(builder)
