# automatically generated by the FlatBuffers compiler, do not modify

# namespace: common

class ValueType(object):
    NONE = 0
    UInt64 = 1
    Int64 = 2
    Double = 3
    Bool = 4
    String = 5
